nginx:
  build: nginx/
  ports:
    - "80:80"
  #links:
  #  - php
  volumes_from:
    - php

php:
  build: php-fpm/
  links:
    - mysql
  volumes_from:
    - wp

mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: very_strong_root_password
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: strong_enought_wordpress_pass
    MYSQL_DATABASE: wordpress

#wp:
#  build: wordpress/
#  volumes:
#    - /var/www
#    - /var/www/wp-content/uploads
